// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzjsdvgabbskeaiupqdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6anNkdmdhYmJza2VhaXVwcWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyOTQzNDYsImV4cCI6MjA2MDg3MDM0Nn0.xYFRKgxGo7FXsCrfZRoky7WTzX2Mqsfw-I0yh4LT2ao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);